/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'activityType' : ActivityType,
  'userId' : Principal,
  'description' : string,
  'timestamp' : Time,
}
export type ActivityType = { 'QuizCompleted' : null } |
  { 'NoteCreated' : null } |
  { 'SubjectCreated' : null } |
  { 'SessionEnded' : null } |
  { 'FlashcardCreated' : null } |
  { 'SessionStarted' : null } |
  { 'FlashcardReviewed' : null };
export interface Flashcard {
  'userId' : Principal,
  'difficulty' : bigint,
  'term' : string,
  'subjectId' : bigint,
  'definition' : string,
}
export interface Note {
  'title' : string,
  'content' : string,
  'userId' : Principal,
  'subjectId' : bigint,
  'timestamp' : Time,
}
export interface Subject {
  'userId' : Principal,
  'icon' : string,
  'name' : string,
  'color' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'totalCardsReviewed' : bigint,
  'quizAverage' : number,
  'totalStudyTimeNanos' : bigint,
  'currentStreak' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFlashcard' : ActorMethod<[string, string, bigint, bigint], bigint>,
  'createNote' : ActorMethod<[string, string, bigint], bigint>,
  'createSubject' : ActorMethod<[string, string, string], bigint>,
  'deleteFlashcard' : ActorMethod<[bigint], undefined>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'endSession' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRecentActivity' : ActorMethod<[], Array<Activity>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'getUserStats' : ActorMethod<[], UserStats>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFlashcardsBySubject' : ActorMethod<[bigint], Array<Flashcard>>,
  'listNotesBySubject' : ActorMethod<[bigint], Array<Note>>,
  'listSubjects' : ActorMethod<[], Array<Subject>>,
  'recordQuiz' : ActorMethod<[bigint, bigint, bigint], bigint>,
  'reviewFlashcard' : ActorMethod<
    [bigint, { 'easy' : null } | { 'hard' : null } | { 'medium' : null }],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startSession' : ActorMethod<[bigint], bigint>,
  'updateFlashcard' : ActorMethod<[bigint, string, string, bigint], undefined>,
  'updateNote' : ActorMethod<[bigint, string, string], undefined>,
  'updateSubject' : ActorMethod<[bigint, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];