/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ActivityType = IDL.Variant({
  'QuizCompleted' : IDL.Null,
  'NoteCreated' : IDL.Null,
  'SubjectCreated' : IDL.Null,
  'SessionEnded' : IDL.Null,
  'FlashcardCreated' : IDL.Null,
  'SessionStarted' : IDL.Null,
  'FlashcardReviewed' : IDL.Null,
});
export const Time = IDL.Int;
export const Activity = IDL.Record({
  'activityType' : ActivityType,
  'userId' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const UserStats = IDL.Record({
  'totalCardsReviewed' : IDL.Nat,
  'quizAverage' : IDL.Float64,
  'totalStudyTimeNanos' : IDL.Int,
  'currentStreak' : IDL.Nat,
});
export const Flashcard = IDL.Record({
  'userId' : IDL.Principal,
  'difficulty' : IDL.Nat,
  'term' : IDL.Text,
  'subjectId' : IDL.Nat,
  'definition' : IDL.Text,
});
export const Note = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'subjectId' : IDL.Nat,
  'timestamp' : Time,
});
export const Subject = IDL.Record({
  'userId' : IDL.Principal,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFlashcard' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'createSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteFlashcard' : IDL.Func([IDL.Nat], [], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'endSession' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRecentActivity' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserStats' : IDL.Func([], [UserStats], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFlashcardsBySubject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Flashcard)],
      ['query'],
    ),
  'listNotesBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Note)], ['query']),
  'listSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'recordQuiz' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'reviewFlashcard' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'easy' : IDL.Null,
          'hard' : IDL.Null,
          'medium' : IDL.Null,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startSession' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'updateFlashcard' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateNote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ActivityType = IDL.Variant({
    'QuizCompleted' : IDL.Null,
    'NoteCreated' : IDL.Null,
    'SubjectCreated' : IDL.Null,
    'SessionEnded' : IDL.Null,
    'FlashcardCreated' : IDL.Null,
    'SessionStarted' : IDL.Null,
    'FlashcardReviewed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Activity = IDL.Record({
    'activityType' : ActivityType,
    'userId' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const UserStats = IDL.Record({
    'totalCardsReviewed' : IDL.Nat,
    'quizAverage' : IDL.Float64,
    'totalStudyTimeNanos' : IDL.Int,
    'currentStreak' : IDL.Nat,
  });
  const Flashcard = IDL.Record({
    'userId' : IDL.Principal,
    'difficulty' : IDL.Nat,
    'term' : IDL.Text,
    'subjectId' : IDL.Nat,
    'definition' : IDL.Text,
  });
  const Note = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'subjectId' : IDL.Nat,
    'timestamp' : Time,
  });
  const Subject = IDL.Record({
    'userId' : IDL.Principal,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFlashcard' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'createSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteFlashcard' : IDL.Func([IDL.Nat], [], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'endSession' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRecentActivity' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserStats' : IDL.Func([], [UserStats], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFlashcardsBySubject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Flashcard)],
        ['query'],
      ),
    'listNotesBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Note)], ['query']),
    'listSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'recordQuiz' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'reviewFlashcard' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'easy' : IDL.Null,
            'hard' : IDL.Null,
            'medium' : IDL.Null,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startSession' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'updateFlashcard' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateNote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };